import React, { useEffect, useState } from 'react';
import axios from 'axios';

const ROLES = {
  super_admin: { label: 'Super Admin', color: '#ff5500', perms: { can_view_dashboard:true, can_manage_assets:true, can_manage_employees:true, can_manage_handovers:true, can_manage_maintenance:true, can_view_audit_logs:true, can_manage_users:true } },
  admin: { label: 'Admin', color: '#10b981', perms: { can_view_dashboard:true, can_manage_assets:true, can_manage_employees:true, can_manage_handovers:true, can_manage_maintenance:true, can_view_audit_logs:false, can_manage_users:false } },
  manager: { label: 'Manager', color: '#3b82f6', perms: { can_view_dashboard:true, can_manage_assets:true, can_manage_employees:false, can_manage_handovers:true, can_manage_maintenance:true, can_view_audit_logs:false, can_manage_users:false } },
  viewer: { label: 'Viewer', color: '#999', perms: { can_view_dashboard:true, can_manage_assets:false, can_manage_employees:false, can_manage_handovers:false, can_manage_maintenance:false, can_view_audit_logs:false, can_manage_users:false } }
};
const PERMISSIONS = [['can_view_dashboard','📊 View Dashboard'],['can_manage_assets','📦 Manage Assets'],['can_manage_employees','👥 Manage Employees'],['can_manage_handovers','🔄 Manage Handovers'],['can_manage_maintenance','🔧 Manage Maintenance'],['can_view_audit_logs','📋 View Audit Logs'],['can_manage_users','🔑 Manage Users']];
const SUPER_ADMIN = 'support@apexingoodcompany.co.uk';

function AdminUsers({ apiUrl, token }) {
  const [users,setUsers]=useState([]), [invites,setInvites]=useState([]), [selected,setSelected]=useState(null), [editing,setEditing]=useState(false), [showForm,setShowForm]=useState(false), [loading,setLoading]=useState(true), [error,setError]=useState(''), [form,setForm]=useState({email:'',role:'admin'});
  const headers={headers:{Authorization:`Bearer ${token}`}};
  const load=async()=>{try{const [u,i]=await Promise.all([axios.get(`${apiUrl}/users`,headers),axios.get(`${apiUrl}/invites`,headers)]);setUsers(u.data);setInvites(i.data);setError('');}catch(e){setError(e.response?.data?.detail||'Failed to load user management data');}finally{setLoading(false);}};
  useEffect(()=>{load();},[]);
  const save=async(data)=>{try{const r=await axios.put(`${apiUrl}/users/${selected.id}`,data,headers);setSelected(r.data);setEditing(false);await load();}catch(e){setError(e.response?.data?.detail||'Failed to update user');}};
  const setActive=async(active)=>{if(selected.email.toLowerCase()===SUPER_ADMIN&&!active){setError('The protected super-admin account cannot be disabled.');return;}if(!window.confirm(active?'Reactivate this user?':'Disable this user?'))return;await save({is_active:active});};
  const invite=async(e)=>{e.preventDefault();try{const r=await axios.post(`${apiUrl}/invites`,form,headers);try{await axios.post(`${apiUrl}/send-invite-email/${r.data.id}`,{},headers);setError(`Invite sent to ${form.email}`);}catch{setError(`Invite created. Manual link: ${window.location.origin}/?token=${r.data.token}`);}setForm({email:'',role:'admin'});setShowForm(false);load();}catch(err){setError(err.response?.data?.detail||'Failed to create invite');}};
  const daysSince=d=>d?Math.max(0,Math.floor((Date.now()-new Date(d).getTime())/86400000)):null;
  const role=ROLES[selected?.role]||ROLES.viewer;
  return <div className="page">
    <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:'.5rem'}}><h1 style={{margin:0,color:'#ff5500',fontSize:'1.8rem'}}>🔑 User Management</h1><button onClick={()=>setShowForm(!showForm)} style={{padding:'.75rem 1.2rem',background:'linear-gradient(135deg,#ff5500,#ff7722)',color:'#fff',border:0,borderRadius:4,fontWeight:700}}>{showForm?'✕ Cancel':'+ Add User'}</button></div>
    <p style={{color:'#777',marginTop:0}}>Security lifecycle: inactive accounts are automatically disabled after <strong style={{color:'#ddd'}}>30 days without a login</strong>. The protected super-admin account is exempt.</p>
    {error&&<div style={{margin:'1rem 0',padding:'1rem',background:'#1a0a0a',borderRadius:4,color:'#f59e0b'}}>{error}</div>}
    {showForm&&<form onSubmit={invite} style={{background:'#0a0a0a',border:'2px solid #1f1f1f',borderRadius:8,padding:'1.5rem',margin:'1.5rem 0',display:'grid',gridTemplateColumns:'1fr 180px auto',gap:'1rem'}}><div className="form-group"><label>Email *</label><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required /></div><div className="form-group"><label>Role</label><select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{Object.entries(ROLES).map(([k,v])=><option key={k} value={k}>{v.label}</option>)}</select></div><button type="submit" style={{alignSelf:'end',padding:'.8rem 1rem'}}>Send Invite</button></form>}
    {invites.length>0&&<div style={{background:'#0a0a0a',border:'2px solid #f59e0b',borderRadius:8,padding:'1rem 1.5rem',marginBottom:'1.5rem'}}><h3 style={{color:'#f59e0b',marginTop:0}}>📧 Pending Invites ({invites.length})</h3>{invites.map(i=><div key={i.id} style={{padding:'.65rem 0',borderBottom:'1px solid #222',color:'#bbb'}}><strong>{i.email}</strong> · {i.role} · expires {new Date(i.expires_at).toLocaleDateString()} <button onClick={()=>navigator.clipboard.writeText(`${window.location.origin}/?token=${i.token}`)} style={{float:'right'}}>Copy Link</button></div>)}</div>}
    <div style={{display:'grid',gridTemplateColumns:'minmax(280px,1fr) 2fr',gap:'1.5rem'}}>
      <div><div style={{display:'flex',justifyContent:'space-between'}}><h2 style={{color:'#ff5500',fontSize:'1.1rem'}}>Accounts</h2><span style={{color:'#777',fontSize:'.8rem',paddingTop:'1.2rem'}}>{users.filter(u=>u.is_active).length} active · {users.filter(u=>!u.is_active).length} disabled</span></div><div style={{background:'#0a0a0a',border:'2px solid #1f1f1f',borderRadius:8,overflow:'hidden',maxHeight:650,overflowY:'auto'}}>{loading?<div className="loading">Loading...</div>:users.map(u=><div key={u.id} onClick={()=>{setSelected(u);setEditing(false)}} style={{padding:'1rem',borderBottom:'1px solid #1f1f1f',cursor:'pointer',opacity:u.is_active?1:.55,borderLeft:selected?.id===u.id?'4px solid #ff5500':'4px solid transparent'}}><div style={{fontWeight:600,color:u.is_active?'#ff5500':'#777'}}>{u.email}</div><div style={{display:'flex',gap:'.4rem',marginTop:'.4rem',alignItems:'center'}}><span style={{fontSize:'.72rem',padding:'.2rem .5rem',borderRadius:3,background:`${ROLES[u.role]?.color||'#666'}20`,color:ROLES[u.role]?.color||'#666'}}>{ROLES[u.role]?.label||u.role}</span><span style={{fontSize:'.7rem',color:u.is_active?'#10b981':'#ef4444'}}>{u.is_active?'ACTIVE':'DISABLED'}</span></div></div>)}{!loading&&users.length===0&&<div className="empty-state">No users</div>}</div></div>
      {selected?<div style={{background:'#0a0a0a',border:'2px solid #1f1f1f',borderRadius:8,padding:'1.75rem'}}>
        <div style={{display:'flex',justifyContent:'space-between',gap:'1rem',alignItems:'start'}}><div><h2 style={{margin:'0 0 .35rem',color:'#ff5500'}}>{selected.email}</h2><div style={{color:'#777'}}>Role: <span style={{color:role.color}}>{role.label}</span> · Created {new Date(selected.created_at).toLocaleDateString()}</div></div>{selected.email.toLowerCase()===SUPER_ADMIN?<span style={{color:'#ff5500',fontWeight:700}}>🔒 PROTECTED</span>:<button onClick={()=>setActive(!selected.is_active)} style={{background:selected.is_active?'#7f1d1d':'#166534',color:'#fff',border:0,borderRadius:4,padding:'.6rem 1rem'}}>{selected.is_active?'Disable User':'Reactivate User'}</button>}</div>
        <div style={{display:'grid',gridTemplateColumns:'repeat(2,1fr)',gap:'1rem',margin:'1.75rem 0'}}><Info label="Status" value={selected.is_active?'Active':'Disabled'} color={selected.is_active?'#10b981':'#ef4444'}/><Info label="Last Login" value={selected.last_login?new Date(selected.last_login).toLocaleString():'Never'}/><Info label="Inactivity" value={selected.last_login?`${daysSince(selected.last_login)} day(s)`:'No login recorded'}/>{selected.disabled_at&&<Info label="Disabled At" value={new Date(selected.disabled_at).toLocaleString()}/>} {selected.disabled_reason&&<Info label="Reason" value={selected.disabled_reason}/>}</div>
        <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:'1rem'}}><h3 style={{color:'#ff5500',margin:0}}>Permissions</h3>{!editing&&<button onClick={()=>setEditing(true)} style={{padding:'.5rem .9rem'}}>Edit</button>}</div>
        {editing?<><div style={{display:'grid',gridTemplateColumns:'repeat(2,1fr)',gap:'.5rem',marginBottom:'1rem'}}>{Object.entries(ROLES).map(([k,v])=><button key={k} onClick={()=>save({role:k,...v.perms})} style={{padding:'.7rem',background:'#111',border:`1px solid ${v.color}`,color:v.color,borderRadius:4}}>{v.label}</button>)}</div><div style={{display:'grid',gridTemplateColumns:'repeat(2,1fr)',gap:'.5rem'}}>{PERMISSIONS.map(([k,label])=><label key={k} style={{padding:'.65rem',background:'#111',borderRadius:4}}><input type="checkbox" checked={!!selected[k]} onChange={e=>setSelected({...selected,[k]:e.target.checked})}/> {label}</label>)}</div><div style={{marginTop:'1rem',display:'flex',gap:'.5rem'}}><button onClick={()=>save(Object.fromEntries(PERMISSIONS.map(([k])=>[k,!!selected[k]])))} style={{background:'#166534',color:'#fff',border:0,padding:'.7rem 1rem'}}>Save Permissions</button><button onClick={()=>setEditing(false)}>Cancel</button></div></>:<div style={{display:'grid',gridTemplateColumns:'repeat(2,1fr)',gap:'.5rem'}}>{PERMISSIONS.map(([k,label])=><div key={k} style={{padding:'.65rem',background:'#111',borderLeft:`4px solid ${selected[k]?'#10b981':'#555'}`,color:selected[k]?'#ddd':'#666'}}>{selected[k]?'✓':'✗'} {label}</div>)}</div>}
      </div>:<div className="empty-state" style={{minHeight:350,display:'flex',alignItems:'center',justifyContent:'center'}}>Select a user to view account health and lifecycle information</div>}
    </div>
  </div>;
}
function Info({label,value,color='#ddd'}){return <div><div style={{fontSize:'.75rem',color:'#777',textTransform:'uppercase',marginBottom:'.25rem'}}>{label}</div><div style={{fontWeight:600,color}}>{value}</div></div>}
export default AdminUsers;
